name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync all non-video files to S3
        run: |
          aws s3 sync . s3://deiontulcidasaws.com \
            --exclude "*.mp4" \
            --delete

      - name: Upload all MP4 files with correct headers
        run: |
          for file in $(find . -type f -name "*.mp4"); do
            key=$(basename "$file")
            echo "Uploading $key with video/mp4 content-type"
            aws s3 cp "$file" "s3://deiontulcidasaws.com/$key" --content-type video/mp4 || echo "⚠️ Skipped $key (permissions or not found)"
          done

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E26D7DKKE16JMN \
            --paths "/*"

      - name: Confirm success
        run: echo "✅ Website successfully deployed and videos preserved."
